### ISSUE TITLE
Error when setting up Exposure Notifications

### ISSUE THREAD

**Issue by TJMusiitwa** [covidtrace/contact_trace_plugin#2]
I am using this plugin whilst borrowing the implementation for on-boarding from the CovidTrace App.
During the call to ```enableExposureNotifications( )```, it returns the following error in the debug console.

> I/flutter (10354): MissingPluginException(No implementation found for method getAuthorizationStatus on channel com.covidtrace/gact_plugin)

The code with the issue:

```
ErrorCode errorFromException(err) {
  return ErrorCode.values[int.parse(err.code)];
}
```

The debug error:

> Exception has occurred.
> NoSuchMethodError (NoSuchMethodError: Class 'MissingPluginException' has no instance getter 'code'.
> Receiver: Instance of 'MissingPluginException'
> Tried calling: code)

Could you kindly provide a solution or fix to this?

PS. even when I tried to compile and run the CovidTrace app directly from the github repository, the switch widget doesn't go into the **true** state.

Thanks.

**Comment by wescarr** [comment]
Hey @TJMusiitwa Are you running this on Android or iOS?

**Comment by TJMusiitwa** [comment]
Hey, I tried running this on Android.

Jonathan Musiitwa
________________________________

**Comment by wescarr** [comment]
I just merged up a PR which completes support for the Android EN API to `master`, so please pull that and let me know how it goes!

**Comment by TJMusiitwa** [comment]
Sure thing I'll let you know...

Jonathan Musiitwa

________________________________

**Comment by wescarr** [comment]
@TJMusiitwa I'm going to close this out since it's getting stale. Feel free to reopen if the issue persists
